version: "3"
services:
    database:
        image: "postgres"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=solight
        ports:
            - "5432:5432"
        volumes:
            - ./resources/solight_setup.sql:/docker-entrypoint-initdb.d/solight_setup.sql
